### ISSUE TITLE
Respring button 

### ISSUE THREAD

**Issue by joshblah555** [iKilledAppl3/AerialChanger#1]
For respringing, you need not use 

` -(void)respring {
    NSTask *task = [[[NSTask alloc] init] autorelease];
    [task setLaunchPath:@"/usr/bin/killall"];
    [task setArguments:[NSArray arrayWithObjects:@"PineBoard", nil]];
    [task launch];
    
} `

but instead: ` -(void)respring {
  system("killall -9 PineBoard");
} `

inside your .mm file. You can also discard the NSTask interface implementation in your header and that /should/ allow for a much more effective respring. If you get compilation errors, be sure to edit `stdlib.h` inside your Xcode SDK to exclude the following ` #if TARGET_OS_EMBEDDED
#define __swift_unavailable_on(osx_msg, ios_msg) __swift_unavailable(ios_msg)
#else
#define __swift_unavailable_on(osx_msg, ios_msg) __swift_unavailable(osx_msg)
#endif

__swift_unavailable_on("Use posix_spawn APIs or NSTask instead.", "Process spawning is unavailable")
__API_AVAILABLE(macos(10.0)) __IOS_PROHIBITED
__WATCHOS_PROHIBITED __TVOS_PROHIBITED `

so that theos doesn't give you a difficult time. Hope this helps!

**Comment by iKilledAppl3** [comment]
I know of that way of doing it lol I used to do that on iOS. But it caused problems when the user did a respring bu when I used NSTask it fixed that issue. I now prefer doing it with NSTask. It does the same thing and isn't deprecated Plus including NSTask is easier than editing the stdlib.h file. Since I have a custom NIC template for myself I don't have to type that out every time.
